export const navItems = ["Discover", "Teams", "Hackathons"];

export const posterData = [
  {
    image: "/images/poster-1.png",
    name: "NeuralNexus: AI 2.0",
    price: "50,000",
    description: "Re-imagine the human-AI interface using next-gen LLMs and edge computing technologies.",
    theme: ["AI","PYTHON","CLOUD"],
    date: "Oct 12 - 14",
    participants: "1,240",
  },
  {
    image: "/images/poster-2.png",
    name: "Decentralize Everything gfndfgndfn",
    price: "120,000",
    description: "The largest Web3 gathering of the year. Build scalable dApps and cross-chain protocols.",
    theme: ["WEB3","SOLIDITY","RUST"],
    date: "Nov 05 - 19",
    participants: "3,800",
  },
  {
    image: "/images/poster-3.png",
    name: "GreenCode Global",
    price: "25,000",
    description: "Solving climate change through data science. Build tools for carbon tracking and sustainable…",
    theme: ["CLIMATE","DATA SCIENCE","REACT"],
    date: "In 3 Days",
    participants: "950",
  },
  {
    image: "/images/poster-4.png",
    name: "FinTech Frontiers",
    price: "120,000",
    description: "Build next-gen autonomous agents using decentralized compute layers. Infrastructure focus",
    theme: ["PYTHON","LLM","WEB3"],
    date: "Dec 01 - 03",
    participants: "1,100",
  },
  {
    image: "/images/poster-5.png",
    name: "CRYPT_SENTINEL_2.0",
    price: "85,000",
    description: "Hardening the digital frontier. Create zero-knowledge proof systems for private financial…",
    theme: ["RUST","ZK-SNARK"],
    date: "Dec 01 - 03",
    participants: "1,100",
  },
  {
    image: "/images/poster-6.png",
    name: "ORBITAL_FRAME_IX",
    price: "250,000",
    description: "Space-tech hackathon focus on satellite communications and orbital data management…",
    theme: ["GO","IOT","SATELLITE"],
    date: "Dec 01 - 03",
    participants: "1,100",
  },
  {
    image: "/images/poster-7.png",
    name: "MORPH_UI_X",
    price: "40,000",
    description: "Designing the future of interactive computing. Focus on Spatial UI and immersive dashboard…",
    theme: ["REACT","THREEJS"],
    date: "Dec 01 - 03",
    participants: "1,100",
  },
  {
    image: "/images/poster-8.png",
    name: "QUANTUM_LEAP_24",
    price: "300,000",
    description: "Building software for the quantum computing era. Simulations, algorithms, and logical gates.",
    theme: ["Q#","PHYSICS"],
    date: "Dec 01 - 03",
    participants: "1,100",
  },
  // {
  //   image: "/images/poster-9.png",
  //   name: "FinTech Frontiers",
  //   price: "40,000",
  //   description: "",
  //   theme: ["FINTECH","GO","SECURITY"],
  //   date: "Dec 01 - 03",
  //   participants: "1,100",
  // },
];
